### ISSUE TITLE
[docker] 500 Server Error

### ISSUE THREAD

**Issue by floari** [JhumanJ/OpnForm#185]
Hi,

after creating a form, there is a 500 server error while trying to accessing the form.

The only error in the logs are related to redis:

`# Failed opening the temp RDB file temp-1859.rdb (in server root dir /app) for saving: Permission denied`

`[2023-09-03 17:28:23] local.ERROR: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. script: 230148430cb441a76f6486ae084405a674e00385, on @user_script:2. {"exception":"[object] (RedisException(code: 0): MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. script: 230148430cb441a76f6486ae084405a674e00385, on @user_script:2. at /app/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116)`

I am using the docker image.
Thanks!

**Comment by JhumanJ** [comment]
Fixed in https://github.com/JhumanJ/OpnForm/commit/08db014cded6544125a6566b1c8e3d2d2c31d62c

**Comment by biohackinginternational** [comment]
Still receiving this error after a few minutes into using it

**Comment by maciejtoporowicz** [comment]
Same thing is happening to me. When it happens, the only workaround is to restart the service.
