### ISSUE TITLE
[DEPLOYMENT] Icons using by OpnForm is missing.

### ISSUE THREAD

**Issue by CookieGMVN** [JhumanJ/OpnForm#605]
**Describe the issue**
The editor UI of OpnForm is broken because the UI can't load icons which is required.

**Deployment Environment**

-   OpnForm Version: 1.4.1
-   Hosting Platform: Self-hosted Server
-   OS: Ubuntu 22.04

**Deployment Method**

-  Docker

**Steps Taken**
Describe the steps you've taken to deploy the application:

1. Clone the repo
2. Generate config by using scripts/generate-config.sh
3. Run `docker compose up -d`

**Error Messages**
The server responsed with:
```json
{
    "message": "The route assets/_nuxt_icon/heroicons.json could not be found.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php",
    "line": 44,
    "trace": [
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php",
            "line": 163,
            "function": "handleMatchedRoute",
            "class": "Illuminate\\Routing\\AbstractRouteCollection",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 763,
            "function": "match",
            "class": "Illuminate\\Routing\\RouteCollection",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 750,
            "function": "findRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 739,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 201,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 144,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/vapor-core/src/Http/Middleware/ServeStaticAssets.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Laravel\\Vapor\\Http\\Middleware\\ServeStaticAssets",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/app/Http/Middleware/AcceptsJsonMiddleware.php",
            "line": 20,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "App\\Http\\Middleware\\AcceptsJsonMiddleware",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/app/Http/Middleware/CustomDomainRestriction.php",
            "line": 22,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "App\\Http\\Middleware\\CustomDomainRestriction",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/app/Http/Middleware/AuthenticateJWT.php",
            "line": 58,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "App\\Http\\Middleware\\AuthenticateJWT",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/app/Http/Middleware/SetLocale.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "App\\Http\\Middleware\\SetLocale",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php",
            "line": 31,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php",
            "line": 51,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/app/Http/Middleware/TrimStrings.php",
            "line": 40,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "App\\Http\\Middleware\\TrimStrings",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php",
            "line": 110,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php",
            "line": 62,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Http\\Middleware\\HandleCors",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php",
            "line": 58,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Http\\Middleware\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 119,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 176,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 145,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/usr/share/nginx/html/public/index.php",
            "line": 51,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}
```

**Configuration Files**
```yml
NUXT_PUBLIC_APP_URL=https://domain.com/
NUXT_PUBLIC_API_BASE=https://domain.com/api
NUXT_PRIVATE_API_BASE=http://ingress/api
NUXT_PUBLIC_ENV=dev
NUXT_API_SECRET=redacted
```
**Logs**
There is no log provided.

**Additional context**
The UI got an error from server when trying to get the JSON files of the icons that is required for it. The UI requested to domain.com/api/nuxt_icons/file.json but it can't, so I think this is a bug.

**Comment by JhumanJ** [comment]
Should be fixed with next release - see https://github.com/JhumanJ/OpnForm/commit/9e19338b54a6f298b86f73b571ee8f95a6ab80b6

**Comment by rl1987** [comment]
The icons are still missing from web UI in self-hosted deployment despite Docker images being manually rebuilt from source.

<img width="1440" alt="Screenshot 2024-11-13 at 13 01 23" src="https://github.com/user-attachments/assets/aafacb08-0362-4814-9cfa-308743274058">
<img width="1440" alt="Screenshot 2024-11-13 at 13 01 32" src="https://github.com/user-attachments/assets/930a4d4f-e6ab-4d2e-a162-54fc39f06e05">
<img width="1440" alt="Screenshot 2024-11-13 at 13 01 40" src="https://github.com/user-attachments/assets/43f0064a-b580-4aab-bdc1-5375c9c4a8fa">

**Comment by brettnpath** [comment]
I'm also having this issue on a fresh install..

![image](https://github.com/user-attachments/assets/f9e8d5f5-b787-46e0-8dbd-5b4496d4cb0f)

**Comment by JhumanJ** [comment]
Can you please try the most recent release? https://github.com/JhumanJ/OpnForm/releases/tag/v1.4.2

**Comment by rl1987** [comment]
I can confirm the icons appear on the form builder now, but not very reliably.

![Screenshot 2024-11-15 at 22 48 24](https://github.com/user-attachments/assets/0257d7b1-34cc-4fb7-a10b-d28e56b826b5)
![Screenshot 2024-11-15 at 22 49 51](https://github.com/user-attachments/assets/73e1fb55-2233-4cd9-9cb8-f6f1fddf29fa)

**Comment by rl1987** [comment]
![Screenshot 2024-11-15 at 22 55 28](https://github.com/user-attachments/assets/e726ef3d-dc05-41c8-9116-3b4a49b915b2)
![Screenshot 2024-11-15 at 22 55 47](https://github.com/user-attachments/assets/a5345ed7-105f-4f30-af7f-492fb3eefe45)

**Comment by brettnpath** [comment]
I have not seen any changes on my end sorry...

**Comment by JonasTrampe** [comment]
I still have this issue, too.

**Comment by splitbrainD** [comment]
Agree, I also have this issue still after upgrading.

And don´t know if it is related but at the same the icons were missing, I can`t see the checkboxes in matrix anymore. The matrix shows up but the radio buttons are not viewable.

**Comment by tomcatcw1980** [comment]
Me too. Still having the same issue.

**Comment by jill88** [comment]
I do as well, I made a discussion post about it.  Thanks, I didn't know what it was.

**Comment by JhumanJ** [comment]
We're still troubleshooting this!

**Comment by brettnpath** [comment]
Sorry @JhumanJ not sure if I'm missing anything here, still no dice for me. For context I can see the radio buttons just fine in the form builder:

![image](https://github.com/user-attachments/assets/7235f6ea-10ff-438f-b340-4e366676fa11)

But not when I view the form
![image](https://github.com/user-attachments/assets/43a47d1f-8d49-40fd-a5f8-c29fefcf3e33)

I've been using an incognito window for testing up to this point, but cleared cache and restarted the browser anyway. This was after I shut down the containers, renamed the existing OpnForm folder then cloned the repo again. 

One other thing I only noticed this morning is possible missing icons and tooltips in the block list on the left:
![image](https://github.com/user-attachments/assets/7f0cb5c2-0401-421e-b93d-cdce23691672)

Anything else I should be doing?

**Comment by JhumanJ** [comment]
Have you pulled the latest docker images? @brettnpath

**Comment by brettnpath** [comment]
> Have you pulled the latest docker images? @brettnpath

I did a git clone after renaming the existing folder, when that did not work I downloaded the ZIP of the latest source code and copied that over the top as well.

If I'm moving the old folder out of the way and then cloning again, is that right?

**Comment by jill88** [comment]
I can confirm the latest version fixed the icons.  Thanks.

**Comment by tomcatcw1980** [comment]
For me, too. Latest version works for me.

**Comment by JhumanJ** [comment]
@brettnpath docker is caching the image version, you need to remove the images and re-download the latest one.

Thanks for the update guys - this was trickier than expected, resolving this one for good!

**Comment by brettnpath** [comment]
Working now I've sorted that - thanks for your patience and the fix!

**Comment by rl1987** [comment]
I can also confirm that icons appear on the web UI as they should now.
