### ISSUE TITLE
[Feature Request] Share link customization

### ISSUE THREAD

**Issue by TotalLag** [JhumanJ/OpnForm#825]
I appreciate the current features for sharing and regenerating links, as well as the QR code generation for easy access. 

- I’d like to request the ability to customize the domain used in these generated links.

Even though I’m logged in via serverA.com, my setup involves a CNAME (serverB.com), and I’d prefer the links to reflect serverB.com instead of serverA.com. Being able to control or configure the link domain would greatly improve the overall user experience.

I cannot simply log into OpnForm serverB.com because I have a reverse proxy setup in such a way that OpnForm administration is only accessible from a specific server.

**Comment by JhumanJ** [comment]
Can you try the following:
- in the back-end .env set a random value to `CADDY_SECRET` and `CADDY_AUTHORIZED_IPS`. This should enabled custom domains
- Then try and follow this guide (without the DNS part) https://help.opnform.com/en/article/how-do-i-use-my-own-domain-9m77g7/

**Comment by TotalLag** [comment]
Just as a test, I tried adding both variables to both API and UI services, but still did not expose the option that's in the guide:

<img width="2077" height="1319" alt="Image" src="https://github.com/user-attachments/assets/fd87f7d6-8899-4436-aa15-e7e8c08de31c" />

I did add a domain under `Settings > Domains`

My services are using private IPv6 fwiw

**Comment by JhumanJ** [comment]
Did you restart the whole docker setup (down and up) before trying? Cache needs to be cleared.
Also please pull the latest docker dev image when this is done https://github.com/JhumanJ/OpnForm/actions/runs/16615566453/job/47007347799.

We fixed an issue with custom SEO in https://github.com/JhumanJ/OpnForm/pull/829.

**Comment by TotalLag** [comment]
Yep, restarted the entire stack including nginx. I'm still not seeing it although I'm pretty sure UI was updated given this was new:

<img width="1561" height="197" alt="Image" src="https://github.com/user-attachments/assets/30958aad-4c44-4d36-9d25-1228689100d6" />

Besides those 2 variables, are there any other condition? Just for fun I also threw in others:

```
  CADDY_SECRET = 'somethingrandom'
  AUTHORIZED_IP = 'ef91:69f3:1677:99ac:bc65:84f4:e26e:f4ee'
  CADDY_AUTHORIZED_IP = 'ef91:69f3:1677:99ac:bc65:84f4:e26e:f4ee'
  CUSTOM_DOMAINS_CADDY_SECRET = 'somethingrandom'
  CUSTOM_DOMAINS_AUTHORIZED_IP = 'ef91:69f3:1677:99ac:bc65:84f4:e26e:f4ee'
```
